#!/system/bin/sh

#set -x

f=/sys/devices/system/cpu/cpu0/cpufreq/stats/time_in_state

freqs=( `cut -f 1 -d ' ' $f` )

prev=( `cut -f 2 -d ' ' $f` )
sleep 1
while true; do
	times=( `cut -f 2 -d ' ' $f` )
	sum=0
	max_non_zero=0
	for i in `seq 0 ${#times[@]}`; do
		[ "0${times[$i]}" -gt 0 ] && max_non_zero=$i
		t=$((times[i]-prev[i]))
		dt[$i]=$t
		sum=$((sum+t))
	done

	#for i in `seq 0 ${#times[@]}`; do
	for i in `seq 0 $max_non_zero`; do
		pct=$((100*dt[i]/sum))
		ms=$((dt[i]*10))
		echo "${freqs[$i]}: ${pct}% ($ms ms)"
	done

	prev=( ${times[@]} )
	echo 
	sleep ${1:-3}
done
